/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    leads: LeadAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    bookings: Booking;
    leads: Lead;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    bookings: BookingsSelect<false> | BookingsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
    header: Header;
    'projects-home': ProjectsHome;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    'projects-home': ProjectsHomeSelect<false> | ProjectsHomeSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Lead;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface LeadAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Manage and organize the central media library for My Studio Channel. Uploaded assets are automatically optimized for use across the platform.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Screen readers and SEO. Empty is OK — it is auto-filled from the file name before save.
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Two-step booking requests submitted from the marketing modal.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings".
 */
export interface Booking {
  id: number;
  name: string;
  email: string;
  phone: string;
  appointmentDate: string;
  message?: string | null;
  source?: string | null;
  preferredDateLocal?: string | null;
  preferredTimeLocal?: string | null;
  timeZone?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Captured emails from future landing forms or integrations.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name?: string | null;
  source?: ('homepage' | 'contact' | 'packages' | 'other') | null;
  /**
   * Optional note from the visitor.
   */
  message?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'leads';
}
/**
 * Core managed pages with SEO metadata in the SEO tab.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL path segment, e.g. about or contact. Defaults to msc1 when empty.
   */
  slug: string;
  /**
   * Short page summary used as fallback meta description.
   */
  description?: string | null;
  pageHero?: {
    enabled?: boolean | null;
    /**
     * Background for the full-width hero (upload in Media first).
     */
    image?: (number | null) | Media;
    eyebrow?: string | null;
    headlineLine1?: string | null;
    headlineLine2?: string | null;
    headlineLine3?: string | null;
    sub?: string | null;
    buttons?: {
      showPrimaryButton?: boolean | null;
      primaryButtonAction?: ('lightbox' | 'link') | null;
      /**
       * When Custom Link is selected (e.g. #msc-contact, /#msc-contact, or https://…).
       */
      primaryButtonLink?: string | null;
      showSecondaryButton?: boolean | null;
      secondaryButtonLabel?: string | null;
      secondaryButtonLink?: string | null;
    };
  };
  /**
   * Compose page sections with anchor IDs for deep-link navigation.
   */
  sections?:
    | (
        | {
            rowInstanceUid?: string | null;
            sectionId: string;
            title?: string | null;
            /**
             * Optional for draft saves. Add body copy before publishing.
             */
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            rowInstanceUid?: string | null;
            sectionId: string;
            title?: string | null;
            items?:
              | {
                  itemInstanceUid?: string | null;
                  /**
                   * Icon label or emoji (for example: camera, mic, or 🎬).
                   */
                  icon: string;
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featureGrid';
          }
        | {
            rowInstanceUid?: string | null;
            sectionId: string;
            title?: string | null;
            /**
             * Paste YouTube or Vimeo URL. Optional if you use a local media file instead.
             */
            videoUrl?: string | null;
            /**
             * Optional local media upload. Add a file or a URL (or both).
             */
            videoFile?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'videoPlayer';
          }
      )[]
    | null;
  /**
   * Main body content rendered on dynamic slug pages with Lexical rich text.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'leads';
        value: number | Lead;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'leads';
        value: number | Lead;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings_select".
 */
export interface BookingsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  appointmentDate?: T;
  message?: T;
  source?: T;
  preferredDateLocal?: T;
  preferredTimeLocal?: T;
  timeZone?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  source?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  pageHero?:
    | T
    | {
        enabled?: T;
        image?: T;
        eyebrow?: T;
        headlineLine1?: T;
        headlineLine2?: T;
        headlineLine3?: T;
        sub?: T;
        buttons?:
          | T
          | {
              showPrimaryButton?: T;
              primaryButtonAction?: T;
              primaryButtonLink?: T;
              showSecondaryButton?: T;
              secondaryButtonLabel?: T;
              secondaryButtonLink?: T;
            };
      };
  sections?:
    | T
    | {
        richText?:
          | T
          | {
              rowInstanceUid?: T;
              sectionId?: T;
              title?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        featureGrid?:
          | T
          | {
              rowInstanceUid?: T;
              sectionId?: T;
              title?: T;
              items?:
                | T
                | {
                    itemInstanceUid?: T;
                    icon?: T;
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        videoPlayer?:
          | T
          | {
              rowInstanceUid?: T;
              sectionId?: T;
              title?: T;
              videoUrl?: T;
              videoFile?: T;
              id?: T;
              blockName?: T;
            };
      };
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Hero carousel, stat row, Programming Styles (7), and Channel preview gallery (7). Rows default to static /public/media assets (after media:sync); clear an image (null) to use site fallbacks for that slot only. Override any slot via relationship → Choose from existing. With SQLite and db.push disabled, if this screen errors run: npm run migrate:sqlite:homepage-hero-secondary-cta, migrate:sqlite:homepage-programming-styles, and migrate:sqlite:homepage-services-gallery
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  heroSlides?:
    | {
        isActive?: boolean | null;
        image: number | Media;
        /**
         * Primary hero CTA URL for this slide. Leave blank to use #msc-contact.
         */
        ctaLink?: string | null;
        /**
         * Outline button with play icon (e.g. View Demos).
         */
        secondaryCtaLabel?: string | null;
        /**
         * Usually #msc-demos to jump to the demos section.
         */
        secondaryCtaLink?: string | null;
        eyebrow?: string | null;
        headlineLine1?: string | null;
        headlineLine2?: string | null;
        headlineLine3?: string | null;
        sub?: string | null;
        /**
         * Per-slide SEO controls used when this slide is the active hero context.
         */
        seo?: {
          /**
           * Suggested title for this slide. Leave blank to fall back to Headline line 1.
           */
          title?: string | null;
          /**
           * Suggested meta description. Leave blank to fall back to Sub text.
           */
          description?: string | null;
          /**
           * Optional social share image. Leave blank to use the slide image.
           */
          image?: (number | null) | Media;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. Leave empty to use the default stat row on the site.
   */
  heroStats?:
    | {
        value: string;
        label: string;
        highlight?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Uncheck to hide the Programming Styles field group below and the “Programming Styles We Support” block on the site. Channel preview gallery is unchanged.
   */
  isStylesVisible?: boolean | null;
  /**
   * Images under “Programming Styles We Support” — seven tiles (genre / format). Defaults match static fallbacks (demo-talkshow, podcast, …). Clear an image to use the site fallback for that slot. Order left-to-right on desktop. Pick existing Media via relationship (Choose from existing). Alt text comes from each Media entry. Rows load collapsed by default (`admin.initCollapsed` + patched Payload form state).
   */
  programmingStyles?:
    | {
        image?: (number | null) | Media;
        /**
         * Short caption under the image (e.g. Interview Talk Show).
         */
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Seven channel preview screenshots (bento layout). Defaults match static fallbacks (Workspace, Data & migration, …). Clear an image to use the site fallback for that slot. Order: first row = large + two stacked smalls, then bottom row of four. Same Media relationship picker as Programming Styles above. Rows load collapsed by default (`admin.initCollapsed` + patched Payload form state).
   */
  servicesGallery?:
    | {
        image?: (number | null) | Media;
        /**
         * Caption shown under the image in the lightbox (e.g. Data & Migration). Alt text comes from the Media entry.
         */
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage primary header navigation links for the marketing site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  /**
   * Add a row whose label is exactly **Pages** (case-sensitive) to show a dropdown of all entries from the Pages collection (slug `home` excluded). The link and any manual submenu rows for that item are ignored at runtime and filled automatically.
   */
  navItems?:
    | {
        label: string;
        /**
         * Use section anchors (e.g. #msc-contact); runtime resolves to # on the home page and /# off home. Full URLs allowed.
         */
        link: string;
        submenu?:
          | {
              label: string;
              link: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage demo projects in one draggable row list, similar to Homepage hero slides.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects-home".
 */
export interface ProjectsHome {
  id: number;
  projectItems?:
    | {
        title: string;
        subtitle: string;
        category: string;
        /**
         * Preview for this project row only. Pick or create Media per slot (independent of other rows).
         */
        image: number | Media;
        /**
         * Live demo URL (https://...) or anchor (#msc-demos).
         */
        demoUrl: string;
        /**
         * Shows this project in the large featured card on the public homepage (Demos section). Only one row should be featured.
         */
        isFeatured?: boolean | null;
        /**
         * Must be ON for this project to appear on the live site. When OFF, saves in admin still work but the homepage ignores this row.
         */
        isVisible?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Site-wide SEO labels. Homepage hero copy lives under Homepage.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Browser tab / share title base.
   */
  siteName: string;
  /**
   * Default meta description (search + social previews).
   */
  tagline?: string | null;
  /**
   * When on, the marketing header stays at the top while scrolling with a glass backdrop. When off, the header scrolls with the page.
   */
  stickyHeader?: boolean | null;
  /**
   * Primary logo used in Header and Footer. Prefer a transparent PNG or SVG-style mark.
   */
  siteLogo?: (number | null) | Media;
  /**
   * Recommended size 32x32px (.ico or .png).
   */
  favicon?: (number | null) | Media;
  /**
   * Default social share image when a page does not define a custom OG image.
   */
  ogImage?: (number | null) | Media;
  /**
   * Appended to page titles (example: "Page Title | My Studio Channel").
   */
  siteTitleSuffix?: string | null;
  /**
   * When enabled, admin alerts are sent for new bookings and leads.
   */
  enableAdminNotifications?: boolean | null;
  /**
   * Primary recipient list for admin alerts. Leave empty to use fallback.
   */
  notificationEmails?:
    | {
        email: string;
        id?: string | null;
      }[]
    | null;
  adminFallbackEmail?: string | null;
  /**
   * This address is used as the from/sender email for notification sends.
   */
  systemFromEmail?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  heroSlides?:
    | T
    | {
        isActive?: T;
        image?: T;
        ctaLink?: T;
        secondaryCtaLabel?: T;
        secondaryCtaLink?: T;
        eyebrow?: T;
        headlineLine1?: T;
        headlineLine2?: T;
        headlineLine3?: T;
        sub?: T;
        seo?:
          | T
          | {
              title?: T;
              description?: T;
              image?: T;
            };
        id?: T;
      };
  heroStats?:
    | T
    | {
        value?: T;
        label?: T;
        highlight?: T;
        id?: T;
      };
  isStylesVisible?: T;
  programmingStyles?:
    | T
    | {
        image?: T;
        label?: T;
        id?: T;
      };
  servicesGallery?:
    | T
    | {
        image?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        label?: T;
        link?: T;
        submenu?:
          | T
          | {
              label?: T;
              link?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects-home_select".
 */
export interface ProjectsHomeSelect<T extends boolean = true> {
  projectItems?:
    | T
    | {
        title?: T;
        subtitle?: T;
        category?: T;
        image?: T;
        demoUrl?: T;
        isFeatured?: T;
        isVisible?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  stickyHeader?: T;
  siteLogo?: T;
  favicon?: T;
  ogImage?: T;
  siteTitleSuffix?: T;
  enableAdminNotifications?: T;
  notificationEmails?:
    | T
    | {
        email?: T;
        id?: T;
      };
  adminFallbackEmail?: T;
  systemFromEmail?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}